#!/usr/bin/env ruby
################################################
## The main Rakefile for the Schoorbs website ##
################################################

## Includes ##

## Tasks ##

task :default => [:clean, :site]

## CLI Tasks ##

task :site do
  sh 'forrest site'
end

task :clean do
  sh 'forrest clean'
end

task :publish_to_schoorbs_xhochy_com => [:site]
task :publish_to_schoorbs_xhochy_com do
  sh 'rm -rf /srv/www/schoorbs.xhochy.com/*'
  sh 'cp -r build/site/* /srv/www/schoorbs.xhochy.com'
end

